site_name: toml-argparse
repo_url: https://github.com/florianmahner/toml-argparse
site_url: https://toml-argparse.github.io
site_author: florianmahner
edit_uri: edit/main/docs/
repo_name: florianmahner/toml-argparse
copyright: Maintained by <a href="https://mahner.space">Florian</a>.

nav:
  - Home: README.me
plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../
            options:
              show_source: true
theme:
  name: material
  feature:
    tabs: false
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/florianmahner/toml-argparse
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/toml-argparse

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true